package dbUtils;

import cardPackage.Card;
import deckPackage.Deck;

/**
 * Communication with db
 */
public interface DBCommInterface {

    void clearDB();

    void switchCardType(Card card);

    /**
     * Creates new card entry from Card object with autogenerated id.
     * @param card Card object
     * @return autogenerated id
     */
    int addCard(Card card);

    void updateCard_content(Card card);

    Card getCard(int card_id);

    void deleteCard(int card_id);

    boolean cardHasNoDeck(int card_id);



    int getCardCountInDeck(int deck_id);

    void updateScoresForDeck(Deck deck);

    String getDeckName(int deck_id);

    /**
     * Creates new deck entry with autogenerated id and specified name.
     * @param deck_name
     * @return autogenerated id
     */
    int addDeck(String deck_name);

    void removeDeck(int deck_id);

    void updateDeckName(int deck_id, String deck_name);

    Deck getDeck(int deck_id);

    Deck[] getDeckList();


    void addCardToDeck_relation(int deck_id, int card_id);

    void removeCardFromDeck_relation(int deck_id, int card_id);

}
